// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0JQkutRO7A3R56g46Y_rJr8lZV_-UPs',
    appId: '1:1029006610708:web:01f3baa34eb4a467337201',
    messagingSenderId: '1029006610708',
    projectId: 'loflow-af550',
    authDomain: 'loflow-af550.firebaseapp.com',
    databaseURL: 'https://loflow-af550-default-rtdb.firebaseio.com',
    storageBucket: 'loflow-af550.firebasestorage.app',
    measurementId: 'G-98KWNKMB9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdI7MuE0hsoaSdQC1q76aa5-SwxV4D6Og',
    appId: '1:1029006610708:android:3f5241c7cd0dd05a337201',
    messagingSenderId: '1029006610708',
    projectId: 'loflow-af550',
    databaseURL: 'https://loflow-af550-default-rtdb.firebaseio.com',
    storageBucket: 'loflow-af550.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzZLbFv1zPH-tNw4fI8wbKx5PkYVb0ZHE',
    appId: '1:1029006610708:ios:d070124e2ff1e3d8337201',
    messagingSenderId: '1029006610708',
    projectId: 'loflow-af550',
    databaseURL: 'https://loflow-af550-default-rtdb.firebaseio.com',
    storageBucket: 'loflow-af550.firebasestorage.app',
    iosBundleId: 'com.example.liflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzZLbFv1zPH-tNw4fI8wbKx5PkYVb0ZHE',
    appId: '1:1029006610708:ios:d070124e2ff1e3d8337201',
    messagingSenderId: '1029006610708',
    projectId: 'loflow-af550',
    databaseURL: 'https://loflow-af550-default-rtdb.firebaseio.com',
    storageBucket: 'loflow-af550.firebasestorage.app',
    iosBundleId: 'com.example.liflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0JQkutRO7A3R56g46Y_rJr8lZV_-UPs',
    appId: '1:1029006610708:web:9c04235b5dff9d1b337201',
    messagingSenderId: '1029006610708',
    projectId: 'loflow-af550',
    authDomain: 'loflow-af550.firebaseapp.com',
    databaseURL: 'https://loflow-af550-default-rtdb.firebaseio.com',
    storageBucket: 'loflow-af550.firebasestorage.app',
    measurementId: 'G-1PD557VL4P',
  );

}